[build]
# Sets base directory for starting a build.
base = "showroom"
# Directory containing deploy-ready HTML files and assets generated as build output.
publish = "dist"
# default built command
command = "npm run build"

[[redirects]]
from = "/menu"
to = "https://showroom-menu.netlify.app/remoteEntry.js"

[[redirects]]
from ="/input"
to = "https://showroom-input.netlify.app/remoteEntry.js"